# Window
# https://alacritty.org/config-alacritty.html
[window]
startup_mode = 'Fullscreen'
padding = { x = 0, y = 0 }

# Font
# https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts
[font]
size = 12
normal = { family = 'CommitMono Nerd Font', style = 'Regular' }

# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_night.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

#Normal colors
[colors.normal]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

